// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForQuestionsBulkInsert implements pgx.CopyFromSource.
type iteratorForQuestionsBulkInsert struct {
	rows                 []QuestionsBulkInsertParams
	skippedFirstNextCall bool
}

func (r *iteratorForQuestionsBulkInsert) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForQuestionsBulkInsert) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
		r.rows[0].Title,
		r.rows[0].Types,
		r.rows[0].IsRequired,
		r.rows[0].SurveysID,
		r.rows[0].Options,
	}, nil
}

func (r iteratorForQuestionsBulkInsert) Err() error {
	return nil
}

func (q *Queries) QuestionsBulkInsert(ctx context.Context, arg []QuestionsBulkInsertParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"questions"}, []string{"id", "created_at", "updated_at", "title", "types", "is_required", "surveys_id", "options"}, &iteratorForQuestionsBulkInsert{rows: arg})
}
