// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Question struct {
	ID         uuid.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	Title      string
	Options    *json.RawMessage
	IsRequired bool
	Types      string
	SurveysID  uuid.UUID
}

type RefreshToken struct {
	ID        uuid.UUID
	TokenHash string
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Response struct {
	ID          uuid.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Response    json.RawMessage
	QuestionsID uuid.UUID
	VoterID     uuid.UUID
	SurveysID   uuid.UUID
}

type Survey struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Title          string
	ExpirationTime pgtype.Timestamptz
	Indentified    bool
	MaxResponse    pgtype.Int4
	UserID         uuid.UUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Email     string
	Password  string
}

type Voter struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Ip        pgtype.Text
	Hash      pgtype.Text
}
