// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Poll struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Config      json.RawMessage
	QuestionsID uuid.UUID
	UserID      uuid.UUID
}

type Question struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
	Questions json.RawMessage
	PollsID   uuid.UUID
}

type Response struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Response    json.RawMessage
	QuestionsID uuid.UUID
	VoterID     uuid.UUID
	PollsID     uuid.UUID
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Email        string
	Password     string
	RefreshToken sql.NullString
}

type Voter struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Ip        sql.NullString
	Hash      sql.NullString
}
