// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Answer struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Body        string
	QuestionsID uuid.UUID
	ResponseID  uuid.UUID
}

type Poll struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	QuestionsID uuid.UUID
	IsPublic    bool
	Expiration  sql.NullTime
}

type Question struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
	PollsID   uuid.UUID
	AnswerID  uuid.UUID
}

type Response struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Response  string
	AnswerID  uuid.UUID
	VoterID   uuid.UUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Password  string
}

type Voter struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Ip        sql.NullString
	Hash      sql.NullString
}
