// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: polls.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSurvey = `-- name: CreateSurvey :one
INSERT INTO surveys (id, created_at, updated_at, title, user_id, config)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id
`

type CreateSurveyParams struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Title     string
	UserID    uuid.UUID
	Config    json.RawMessage
}

func (q *Queries) CreateSurvey(ctx context.Context, arg CreateSurveyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSurvey,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.UserID,
		arg.Config,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
