// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: polls.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createPoll = `-- name: CreatePoll :one
INSERT INTO polls (id, created_at, updated_at, title, user_id, config)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id
`

type CreatePollParams struct {
	Title  string
	UserID uuid.UUID
	Config json.RawMessage
}

func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPoll, arg.Title, arg.UserID, arg.Config)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
