// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (id, created_at, updated_at, title, types, is_required ,surveys_id, options)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id
`

type CreateQuestionParams struct {
	ID         uuid.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	Title      string
	Types      string
	IsRequired bool
	SurveysID  uuid.UUID
	Options    *json.RawMessage
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Types,
		arg.IsRequired,
		arg.SurveysID,
		arg.Options,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getQuestionsWithSurveyid = `-- name: GetQuestionsWithSurveyid :many
select id, created_at, updated_at, title, options, is_required, types, surveys_id 
from questions 
where surveys_id = $1
`

func (q *Queries) GetQuestionsWithSurveyid(ctx context.Context, surveysID uuid.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, getQuestionsWithSurveyid, surveysID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Options,
			&i.IsRequired,
			&i.Types,
			&i.SurveysID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type QuestionsBulkInsertParams struct {
	ID         uuid.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	Title      string
	Types      string
	IsRequired bool
	SurveysID  uuid.UUID
	Options    *json.RawMessage
}
