// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (id, created_at, updated_at, title, polls_id, questions)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, title, questions, polls_id
`

type CreateQuestionParams struct {
	Title     string
	PollsID   uuid.UUID
	Questions json.RawMessage
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion, arg.Title, arg.PollsID, arg.Questions)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Questions,
		&i.PollsID,
	)
	return i, err
}
