// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRefreshToken = `-- name: AddRefreshToken :exec
INSERT INTO refresh_tokens (id, token_hash, user_id, created_at, expires_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type AddRefreshTokenParams struct {
	ID        uuid.UUID
	TokenHash string
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) AddRefreshToken(ctx context.Context, arg AddRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, addRefreshToken,
		arg.ID,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const getUserFromRefreshToken = `-- name: GetUserFromRefreshToken :one
SELECT users.id, users.created_at, users.updated_at, users.email, users.password
FROM refresh_tokens JOIN users ON users.id = refresh_token.user_id
WHERE refresh_tokens.token_hash = $1
AND refresh_tokens.revoked_at = NUll
AND refresh_tokens.expires_at > NOW()
`

func (q *Queries) GetUserFromRefreshToken(ctx context.Context, tokenHash string) (User, error) {
	row := q.db.QueryRow(ctx, getUserFromRefreshToken, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}
