// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: responses.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createResponse = `-- name: CreateResponse :exec
INSERT INTO responses (id, created_at, updated_at, response, survey_id, voter_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type CreateResponseParams struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Response  json.RawMessage
	SurveyID  uuid.UUID
	VoterID   uuid.UUID
}

func (q *Queries) CreateResponse(ctx context.Context, arg CreateResponseParams) error {
	_, err := q.db.Exec(ctx, createResponse,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Response,
		arg.SurveyID,
		arg.VoterID,
	)
	return err
}
