// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: survey.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateSurveyParams struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Title          string
	UserID         uuid.UUID
	ExpirationTime pgtype.Timestamptz
	Indentified    bool
	MaxResponse    pgtype.Int4
}

const createSurvey = `-- name: CreateSurvey :one
INSERT INTO surveys (id, created_at, updated_at, title, user_id, expiration_time, indentified, max_response)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id
`

type CreateSurveyParams struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Title          string
	UserID         uuid.UUID
	ExpirationTime pgtype.Timestamptz
	Indentified    bool
	MaxResponse    pgtype.Int4
}

func (q *Queries) CreateSurvey(ctx context.Context, arg CreateSurveyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSurvey,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.UserID,
		arg.ExpirationTime,
		arg.Indentified,
		arg.MaxResponse,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSurveyByIdUserId = `-- name: GetSurveyByIdUserId :one
Select id, created_at, updated_at, title, expiration_time, indentified, max_response, is_published, user_id
FROM surveys
WHERE surveys.id = $1 AND surveys.user_id = $2
`

type GetSurveyByIdUserIdParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetSurveyByIdUserId(ctx context.Context, arg GetSurveyByIdUserIdParams) (Survey, error) {
	row := q.db.QueryRow(ctx, getSurveyByIdUserId, arg.ID, arg.UserID)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.ExpirationTime,
		&i.Indentified,
		&i.MaxResponse,
		&i.IsPublished,
		&i.UserID,
	)
	return i, err
}

const setIsPublish = `-- name: SetIsPublish :execresult
UPDATE surveys
SET is_published = $1
WHERE id = $2 AND user_id = $3
`

type SetIsPublishParams struct {
	IsPublished bool
	ID          uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) SetIsPublish(ctx context.Context, arg SetIsPublishParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setIsPublish, arg.IsPublished, arg.ID, arg.UserID)
}
