// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateUserParams struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Email     string
	Password  string
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, password)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, email, password
`

type CreateUserParams struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Email     string
	Password  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Email,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const deleteTestUsers = `-- name: DeleteTestUsers :exec
DELETE FROM users WHERE email LIKE 'user%@testsurvy.com'
`

func (q *Queries) DeleteTestUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteTestUsers)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, email, password FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const resetAllUsers = `-- name: ResetAllUsers :exec
DELETE FROM users
`

func (q *Queries) ResetAllUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetAllUsers)
	return err
}

const userExist = `-- name: UserExist :one
SELECT EXISTS (
  SELECT 1
  FROM users
  WHERE email = $1
)
`

func (q *Queries) UserExist(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExist, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
