// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voter.sql

package database

import (
	"context"
	"database/sql"
)

const createVoter = `-- name: CreateVoter :one
INSERT INTO voter (id, created_at, updated_at, ip, hash)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, ip, hash
`

type CreateVoterParams struct {
	Ip   sql.NullString
	Hash sql.NullString
}

func (q *Queries) CreateVoter(ctx context.Context, arg CreateVoterParams) (Voter, error) {
	row := q.db.QueryRowContext(ctx, createVoter, arg.Ip, arg.Hash)
	var i Voter
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ip,
		&i.Hash,
	)
	return i, err
}
