-- +goose Up
ALTER TABLE surveys
ADD COLUMN user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE questions
ADD COLUMN surveys_id UUID NOT NULL REFERENCES surveys(id) ON DELETE CASCADE;

ALTER TABLE responses
ADD COLUMN questions_id UUID NOT NULL REFERENCES questions(id)ON DELETE CASCADE,
ADD COLUMN voter_id UUID NOT NULL REFERENCES voter(id) ON DELETE CASCADE,
ADD COLUMN surveys_id UUID NOT NULL REFERENCES surveys(id) ON DELETE CASCADE;

-- +goose Down
ALTER TABLE surveys
DROP COLUMN user_id;

ALTER TABLE questions
DROP COLUMN surveys_id;

ALTER TABLE responses
DROP COLUMN questions_id,
DROP COLUMN voter_id,
DROP COLUMN surveys_id;
