// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID        uuid.UUID
	TokenHash string
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Response struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Response  json.RawMessage
	VoterID   uuid.UUID
	SurveyID  uuid.UUID
}

type Survey struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Title          string
	ExpirationTime pgtype.Timestamptz
	MaxResponse    pgtype.Int4
	IsPublished    bool
	Questions      json.RawMessage
}

type User struct {
	ID           uuid.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Email        string
	Password     string
	RefreshToken pgtype.Text
}

type Voter struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Ip        pgtype.Text
	Hash      pgtype.Text
}
