// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BulkEnterQuestionsParams struct {
	ID           uuid.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Title        string
	QuestionType string
	Choice       []string
	IsRequired   bool
	SurveyID     uuid.UUID
}

const getQuestionsFromSurveyId = `-- name: GetQuestionsFromSurveyId :many
SELECT id, created_at, updated_at, title, question_type, choice, is_required
FROM questions
WHERE survey_id = $1
`

type GetQuestionsFromSurveyIdRow struct {
	ID           uuid.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Title        string
	QuestionType string
	Choice       []string
	IsRequired   bool
}

func (q *Queries) GetQuestionsFromSurveyId(ctx context.Context, surveyID uuid.UUID) ([]GetQuestionsFromSurveyIdRow, error) {
	rows, err := q.db.Query(ctx, getQuestionsFromSurveyId, surveyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuestionsFromSurveyIdRow
	for rows.Next() {
		var i GetQuestionsFromSurveyIdRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.QuestionType,
			&i.Choice,
			&i.IsRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
