// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: responses.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createResponse = `-- name: CreateResponse :one
INSERT INTO responses (id, created_at, updated_at, response, survey_id, voter_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, response, voter_id, survey_id, question_id, choice
`

type CreateResponseParams struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Response  json.RawMessage
	SurveyID  uuid.UUID
	VoterID   uuid.UUID
}

func (q *Queries) CreateResponse(ctx context.Context, arg CreateResponseParams) (Response, error) {
	row := q.db.QueryRow(ctx, createResponse,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Response,
		arg.SurveyID,
		arg.VoterID,
	)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Response,
		&i.VoterID,
		&i.SurveyID,
		&i.QuestionID,
		&i.Choice,
	)
	return i, err
}
