// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: survey.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateSurveyParams struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Title          string
	UserID         uuid.UUID
	ExpirationTime pgtype.Timestamptz
	MaxResponse    pgtype.Int4
}

const createSurvey = `-- name: CreateSurvey :one
INSERT INTO surveys (id, created_at, updated_at, title, user_id, expiration_time, max_response)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id
`

type CreateSurveyParams struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Title          string
	UserID         uuid.UUID
	ExpirationTime pgtype.Timestamptz
	MaxResponse    pgtype.Int4
}

func (q *Queries) CreateSurvey(ctx context.Context, arg CreateSurveyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSurvey,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.UserID,
		arg.ExpirationTime,
		arg.MaxResponse,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAllUserSurveys = `-- name: GetAllUserSurveys :many
Select id, user_id, created_at, updated_at, title, expiration_time, max_response, is_published
FROM surveys
WHERE user_id = $1
ORDER BY updated_at asc
`

func (q *Queries) GetAllUserSurveys(ctx context.Context, userID uuid.UUID) ([]Survey, error) {
	rows, err := q.db.Query(ctx, getAllUserSurveys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Survey
	for rows.Next() {
		var i Survey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.ExpirationTime,
			&i.MaxResponse,
			&i.IsPublished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSurveyByIdIsPublish = `-- name: GetSurveyByIdIsPublish :one
Select id, user_id, created_at, updated_at, title, expiration_time, max_response, is_published
FROM surveys
WHERE surveys.id = $1 AND is_published
`

func (q *Queries) GetSurveyByIdIsPublish(ctx context.Context, id uuid.UUID) (Survey, error) {
	row := q.db.QueryRow(ctx, getSurveyByIdIsPublish, id)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.ExpirationTime,
		&i.MaxResponse,
		&i.IsPublished,
	)
	return i, err
}

const getSurveyByIdUserId = `-- name: GetSurveyByIdUserId :one
Select id, user_id, created_at, updated_at, title, expiration_time, max_response, is_published
FROM surveys
WHERE surveys.id = $1 AND surveys.user_id = $2
`

type GetSurveyByIdUserIdParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetSurveyByIdUserId(ctx context.Context, arg GetSurveyByIdUserIdParams) (Survey, error) {
	row := q.db.QueryRow(ctx, getSurveyByIdUserId, arg.ID, arg.UserID)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.ExpirationTime,
		&i.MaxResponse,
		&i.IsPublished,
	)
	return i, err
}

const setIsPublish = `-- name: SetIsPublish :execresult
UPDATE surveys
SET is_published = $1
WHERE id = $2 AND user_id = $3
`

type SetIsPublishParams struct {
	IsPublished bool
	ID          uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) SetIsPublish(ctx context.Context, arg SetIsPublishParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setIsPublish, arg.IsPublished, arg.ID, arg.UserID)
}
