// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voter.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVoter = `-- name: CreateVoter :one
INSERT INTO voters (id, created_at, updated_at, ip, hash)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, ip, hash
`

type CreateVoterParams struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Ip        pgtype.Text
	Hash      pgtype.Text
}

func (q *Queries) CreateVoter(ctx context.Context, arg CreateVoterParams) (Voter, error) {
	row := q.db.QueryRow(ctx, createVoter,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Ip,
		arg.Hash,
	)
	var i Voter
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ip,
		&i.Hash,
	)
	return i, err
}
